import { TableColumns } from "@shared/models/list-table.interface";
import { SearchOptions } from "@shared/models/search-options.interface";
import { GenericValidators } from "@shared/validators/generic-validators";
import { ProductDetailsResponse, SaleResponse } from "../../models/sale-response.interface";
import { IconsService } from "@shared/services/icons.service";

const searchOptions: SearchOptions[] = [
  {
    label: "Comprobante",
    value: 1,
    placeholder: "Buscar por comprobante",
    validation: [GenericValidators.alphanumeric],
    validation_desc: "Sólo se permite letras y/o números en esta búsqueda.",
    icon: "icName",
  },
];

const searchOptionsProducts: SearchOptions[] = [
  {
    label: "Código",
    value: 1,
    placeholder: "Buscar por Código",
    validation: [GenericValidators.alphanumeric],
    validation_desc: "Sólo se permite letras y/o números en esta búsqueda.",
    icon: "icName",
  },
  {
    label: "Nombre",
    value: 2,
    placeholder: "Buscar por Nombre",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite letras en esta búsqueda.",
    icon: "icName",
  },
];

const tableColumns: TableColumns<SaleResponse>[] = [
  {
    label: "COMPROBANTE",
    cssLabel: ["font-bold", "text-sm"],
    property: "voucherDescription",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "badge",
    sticky: true,
    sort: true,
    sortProperty: "voucherDescription",
    visible: true,
    download: true,
  },
  {
    label: "N° COMPROBANTE",
    cssLabel: ["font-bold", "text-sm"],
    property: "voucherNumber",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "textUppercase",
    sticky: true,
    sort: true,
    sortProperty: "voucherNumber",
    visible: true,
    download: true,
  },
  {
    label: "CLIENTE",
    cssLabel: ["font-bold", "text-sm"],
    property: "client",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "textUppercase",
    sticky: true,
    sort: true,
    sortProperty: "client",
    visible: true,
    download: true,
  },
  {
    label: "ALMACÉN",
    cssLabel: ["font-bold", "text-sm"],
    property: "warehouse",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: true,
    sort: true,
    sortProperty: "warehouse",
    visible: true,
    download: true,
  },
  {
    label: "MONTO TOTAL",
    cssLabel: ["font-bold", "text-sm"],
    property: "totalAmount",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "currency",
    sticky: true,
    sort: true,
    sortProperty: "totalAmount",
    visible: true,
    download: true,
  },
  {
    label: "F. DE VENTA",
    cssLabel: ["font-bold", "text-sm"],
    property: "dateOfSale",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "datetime",
    sticky: true,
    sort: true,
    sortProperty: "dateOfSale",
    visible: true,
    download: true,
  },
  {
    label: "",
    cssLabel: [],
    property: "icView",
    cssProperty: [],
    type: "icon",
    action: "viewDetail",
    sticky: false,
    sort: false,
    visible: true,
    download: false,
  },
  {
    label: "",
    cssLabel: [],
    property: "icInvoice",
    cssProperty: [],
    type: "icon",
    action: "exportInvoice",
    sticky: false,
    sort: false,
    visible: true,
    download: false,
  },
  {
    label: "",
    cssLabel: [],
    property: "icCancel",
    cssProperty: [],
    type: "icon",
    action: "cancel",
    sticky: false,
    sort: false,
    visible: true,
    download: false,
  },
];

const tableColumnsProducts: TableColumns<ProductDetailsResponse>[] = [
  {
    label: "",
    cssLabel: ["font-bold", "text-xxs"],
    property: "image",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    type: "image",
    sticky: false,
    sort: true,
    sortProperty: "image",
    visible: true,
    download: true,
  },
  {
    label: "CÓDIGO",
    cssLabel: ["font-bold", "text-xxs"],
    property: "code",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    type: "textUppercase",
    sticky: false,
    sort: true,
    sortProperty: "code",
    visible: true,
    download: true,
  },
  {
    label: "NOMBRE",
    cssLabel: ["font-bold", "text-xxs"],
    property: "name",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    subProperty: "category",
    cssSubProperty: ["text-xxs", "text-am-gray", "uppercase", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "name",
    visible: true,
    download: true,
  },
  {
    label: "CANTIDAD",
    cssLabel: ["font-bold", "text-xxs"],
    property: "quantity",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    type: "quantitySale",
    sticky: false,
    sort: true,
    visible: true,
  },
  {
    label: "PRECIO U.",
    cssLabel: ["font-bold", "text-xxs"],
    property: "unitSalePrice",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    type: "unitSalePrice",
    sticky: false,
    sort: true,
    visible: true,
  },
  {
    label: "STOCK ACTUAL",
    cssLabel: ["font-bold", "text-xxs"],
    property: "currentStock",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    type: "number",
    sticky: false,
    sort: true,
    visible: true,
  },
  {
    label: "TOTAL",
    cssLabel: ["font-bold", "text-xxs"],
    property: "totalAmount",
    cssProperty: ["font-semibold", "text-xs", "text-left"],
    type: "totalAmount",
    sticky: false,
    sort: true,
    visible: true,
  },
  {
    label: "",
    cssLabel: [],
    property: "icAdd",
    cssProperty: [],
    type: "icon",
    action: "addDetail",
    sticky: false,
    sort: false,
    visible: true,
    download: false,
  },
];

const filters = {
  numFilter: 0,
  textFilter: "",
  startDate: "",
  endDate: "",
  refresh: false,
};

const resetFilters = {
  numFilter: 0,
  textFilter: "",
  startDate: "",
  endDate: "",
  refresh: false,
};

const getInputs: string = "";

export const componentSettings = {
  icSale: IconsService.prototype.getIcon("icSales"),
  tableColumns,
  tableColumnsProducts,
  searchOptions,
  searchOptionsProducts,
  initialSort: "Id",
  initialSortDir: "desc",
  filters,
  resetFilters,
  getInputs,
  filename: "listado-de-ventas",
};